apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jira-mcp
  labels:
    app: jira-mcp
spec:
  to:
    kind: Service
    name: jira-mcp
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
