apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ghost-tls
spec:
  ports:
    - name: https
      port: 443
      targetPort: 4180
      protocol: TCP
  selector:
    app: ghost
  type: ClusterIP
